#!/bin/bash
#################################
# Author: Eunchong Kim
# Email: eunchong.kim at cern.ch
# Date: April 2019
# Project: Local Database for YARR
# Description: Bash completion for sync tool
#################################
# This makes heavy use of ksh style extended globs and contains Linux specific
# code for completing the parameter to the -fstype option.

_localdbtool_sync() {
    local cur prev cword
    _get_comp_words_by_ref -n : cur prev cword

    if [ "${cword}" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "--config --host --port --username --password --mhost --mport --musername --mpassword" -- "${cur}") )
    elif [ "${cword}" -eq 2 ]; then
        if [ "${prev}" = "--config" ]; then
            compopt -o filenames
            COMPREPLY=( $(compgen -f -- ${cur}) )
        else
            COMPREPLY=( $(compgen -W "--host --port --username --password --mhost --mport --musername --mpassword" -- "${cur}") )
        fi
    elif [ "${cword}" -eq 3 ]; then
        if [ "${prev}" = "--sync-opt" ]; then
            COMPREPLY=( $(compgen -W "commit push fetch pull" -- "${cur}") )
        else
            COMPREPLY=( $(compgen -W "--host --port --username --password --mhost --mport --musername --mpassword" -- "${cur}") )
        fi
    fi
}
complete -F _localdbtool_sync localdbtool-sync.py
