#!/bin/bash
#################################
# Author: Eunchong Kim
# Email: eunchong.kim at cern.ch
# Date: April 2019
# Project: Local Database for YARR
# Description: Bash completion for archive tool
#################################
# This makes heavy use of ksh style extended globs and contains Linux specific
# code for completing the parameter to the -fstype option.

_localdbtool_archive() {
    local cur prev cword
    _get_comp_words_by_ref -n : cur prev cword
  
    if [ "${cword}" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "--config --data_path --archive_path --n_archives" -- "${cur}") )
    else
        if [ "${prev}" = "--config" ]; then
            _filedir
        elif [ "${prev}" = "--data_path" ]; then
            _filedir
        elif [ "${prev}" = "--archive_path" ]; then
            _filedir
        elif [ "${prev}" = "--n_archives" ]; then
            COMPREPLY=( $(compgen -W "1 2 3 4 5 6 ... #Insert_#_archives" -- "${cur}") )
        else
            COMPREPLY=( $(compgen -W "--data_path --archive_path --n_archives" -- "${cur}") )
        fi
    fi
}
complete -F _localdbtool_archive localdbtool-archive.sh
